### PR TITLE
pain.csv database and MKDAscript.m

### PR DESCRIPTION
**Pull request by AlexBowring**
This PR contains the pain.csv database used for the MKDA analysis as well as a MKDAscript.m for running the analysis.

### CODE REVIEW

**Comment by cmaumet** [comment]
Hi @AlexBowring: thanks for this! Could you comment this script to mention any value you have to manually type in when running the script (e.g. selection of the contrast)?

**Comment by AlexBowring** [comment]
Hi @cmaumet, I have updated this PR with the results output from matlab file and commented on the script as you requested above.

**Comment by cmaumet** [comment]
Thank you @AlexBowring! To help replicate the analysis you did, could you also explicitely state in the comments which option you used?

For example with "During this stage the [missing _user_] specifies which variables (regressors) will be used during the analysis". Could you add which regressor you actually used? How is this entered into the program: using the regressor name, a numerical index...? If you can make a copy in the comment of what you typed in at each stage that would be very helpful for a user trying to replicate this exact analysis.

**Comment by AlexBowring** [comment]
Okay @cmaumet I have updated the script again, let me know if it is clear now

**Comment by cmaumet** [comment]
That looks good!

**Pull request merged**
